name: "Collect & Publish"

on:
 schedule:
   - cron:  '0/15 * * * *'
  # push:
  #   branches:
  #     - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: jorgebg/stateful-action@v0.1
      with:
        branch: state

    - uses: jorgebg/stateful-action@v0.1
      with:
        branch: gh-pages

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Set up Git
      run: |
        git config user.email "airquality@jorgebg.com"
        git config user.name "Air Quality Bot"

    - name: Install dependencies
      run: |
        pip3 install -r requirements.txt

    - name: Collect the data
      env:
        AWS_DEFAULT_REGION: 'eu-west-1'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        python3 collector.py

    - name: Publish the data
      run: |
        python3 publisher.py
